# Generated by Django 4.2 on 2023-05-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_seller", "0010_alter_salesmanprofile_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="discount",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
