# Generated by Django 4.2 on 2023-05-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_products", "0012_alter_productmodel_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("strength", models.CharField(max_length=100)),
                ("generics", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("consumption_type", models.CharField(max_length=255)),
            ],
        ),
    ]
