# Generated by Django 4.2 on 2023-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_products", "0014_productmodel_is_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinedetails",
            name="company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="medicinedetails",
            name="consumption_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="medicinedetails",
            name="generics",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="medicinedetails",
            name="strength",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
