# Generated by Django 4.2 on 2023-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_products", "0015_alter_medicinedetails_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="barcode_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
